enabled: true
settings:
  redirect_url: ''
  client_id: 1027804868438-no5s5mla0i0apmvogvaqm1ldrtf0m16v.apps.googleusercontent.com
  client_secret: kFUNlpTGUESnMPkHmjfey4yh
_core:
  default_config_hash: h0ctmI-lSknN6e9qvO8PKjAPEeopeDR4FnxTYhGcD1k
