enabled: true
settings:
  redirect_url: ''
  client_id: '377447186398925'
  client_secret: 665f5b572627ba3519fd781c34588c61
  api_version: v2.11
_core:
  default_config_hash: XE2MqevnEK7g2Hi3bBsxJUUcbYQBm9AjQR6foDyycRY
